export const FETCH_TWEETS_REQUEST = "FETCH_TWEETS_REQUEST";
export const FETCH_TWEETS_SUCCESS = "FETCH_TWEETS_SUCCESS";
export const FETCH_TWEETS_FAILURE = "FETCH_TWEETS_FAILURE";
export const SEARCH_TRENDS_REQUEST = "SEARCH_TRENDS_REQUEST";
export const SEARCH_TRENDS_SUCCESS = "SEARCH_TRENDS_SUCCESS";
export const SEARCH_TRENDS_FAILURE = "SEARCH_TRENDS_FAILURE";
export const SELECT_TWEET = "SELECT_TWEET";
